---
- name: Configure Windows honeypot
  hosts: honeypot
  gather_facts: no
  collections:
    - ansible.windows
  tasks:
    - name: Enable RDP via registry
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword

    - name: Ensure Remote Desktop service is running
      win_service:
        name: TermService
        start_mode: auto
        state: started

    - name: Create rdpuser account
      win_user:
        name: rdpuser
        password: "{{ rdpuser_password }}"
        state: present
        groups:
          - Remote Desktop Users
          - Administrators

    - name: Allow RDP TCP in firewall
      win_firewall_rule:
        name: RDP-TCP
        localport: 3389
        protocol: tcp
        direction: in
        action: allow
        state: present

    - name: Allow RDP UDP in firewall
      win_firewall_rule:
        name: RDP-UDP
        localport: 3389
        protocol: udp
        direction: in
        action: allow
        state: present

    - name: WinRM quickconfig
      win_shell: winrm quickconfig -force

    - name: Allow unencrypted WinRM
      win_shell: winrm set winrm/config/service @{AllowUnencrypted="true"}

    - name: Enable basic auth for WinRM
      win_shell: winrm set winrm/config/service/auth @{Basic="true"}

    - name: Allow remote access for WinRM
      win_shell: winrm set winrm/config/service @{AllowRemoteAccess="true"}

    - name: Open WinRM firewall
      win_firewall_rule:
        name: WinRM-TCP
        localport: 5985
        protocol: tcp
        direction: in
        action: allow
        state: present

    - name: Test WinRM connectivity
      win_ping:

- name: Deploy Suricata and Filebeat
  hosts: sensor
  gather_facts: no
  become: yes
  tasks:
    - name: Copy docker-compose file
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: /opt/honeypot/docker-compose.yml

    - name: Copy Suricata configuration
      copy:
        src: "{{ playbook_dir }}/../suricata/"
        dest: /opt/honeypot/suricata

    - name: Copy Filebeat configuration
      copy:
        src: "{{ playbook_dir }}/../filebeat.yml"
        dest: /opt/honeypot/filebeat.yml

    - name: Start containers
      command: docker-compose up -d
      args:
        chdir: /opt/honeypot
